name: Preprocess Dataset

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Bisa dijalankan manual dari GitHub

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn scipy

      - name: Jalankan Preprocessing
        run: |
          python scripts/automate_Donny.py

      - name: Upload Dataset Bersih
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-dataset
          path: computer_prices_clean.csv
